baseURL = "https://www.skyzh.dev/"
copyright = "© Alex Chi"
languageCode = "en-us"
theme = "hugo-ink"
title = "Alex Chi"
# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"

paginate = 3 # articles per page

googleAnalytics = "UA-52525161-8"

[params]
avatar = "https://avatars.githubusercontent.com/u/4198311"
mode = "light"
featherIconsCDN = false
# subtitle = "Code for fun"
excludedTypes = ["page", "pages"]

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/skyzh"
